name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        cxx: [clang++, g++, cl]
        std: [14, 17, 20]
        build_type: [Debug]
        generators: [Ninja]
        exclude:
          - os: windows-latest
            cxx: clang++
          - os: ubuntu-latest
            cxx: clang++
          - os: ubuntu-latest
            cxx: cl
          - os: macos-latest
            cxx: g++
          - os: macos-latest
            cxx: cl

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH env
        if: startsWith(matrix.os, 'windows') && matrix.cxx == 'cl'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version

      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install cmake ninja
          ninja --version
          cmake --version

      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_CXX_STANDARD:STRING=${{ matrix.std }} \
            -DSML_BUILD_EXAMPLES=ON \
            -DSML_BUILD_TESTS=ON \
            -G "${{ matrix.generators }}"

      - name: Build
        shell: bash
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Test
        shell: bash
        run: ctest --output-on-failure .
